### ISSUE TITLE
Rework and improvement

### ISSUE THREAD

**Issue by bastienvoirin** [bastienvoirin/edward#1]
### Todo
- [ ] Overall structure rework
- [ ] Smarter, smoother attitude
- [ ] Better CSS style
- [ ] Performance improvements
- [ ] Neater code
- [ ] Optional issue report generator
